convexengineering/gpkit

- gpkit/tests/t_nomials.py
> test integer division on posynomials

- gpkit/_mosek/cli_expopt.py
- gpkit/build.py
- gpkit/geometric_program.py
- setup.py
The build script may well be worth a full refactoring at some point, but for now this deals with issues discovered by @galbramc (and incorporates his fixes and suggestions).
Confirmed on my linux computer, will test on my windows computer.
Please test on Macs!
> Build script improvements

- gpkit/tests/helpers.py
- gpkit/tests/run_tests.py
- gpkit/tests/t_constraints.py
- gpkit/tests/t_geometric_program.py
- gpkit/tests/t_gp_solution_array.py
- gpkit/tests/t_nomials.py
- gpkit/tests/t_posy_array.py
- gpkit/tests/t_sub.py
- gpkit/tests/t_vars.py
Mostly pylint and minor cosmetics.
Also fixed some tests that weren't being run.
> pylint tests and run for all solvers

- gpkit/posyarray.py
- gpkit/tests/t_posy_array.py
- gpkit/tests/t_vars.py
> Ndarray subclassing

- gpkit/tests/t_geometric_program.py
These don't work right now, but should soon!
> Trivial SP tests

- gpkit/tests/t_geometric_program.py
> Revert "Trivial SP tests"

- gpkit/geometric_program.py
- gpkit/interactive/printing.py
- gpkit/nomials.py
- gpkit/posyarray.py
- gpkit/tests/t_nomials.py
- gpkit/varkey.py
Proposed fix for #275 
* pep8
* removes `vkSortBy`
* un-protects `_latex()` methods
> Fix printing bugs

- docs/source/advancedcommands.rst
- gpkit/interactive/plotting.py
- gpkit/nomials.py
- gpkit/substitution.py
- gpkit/tests/t_sub.py
- gpkit/tests/t_vars.py
- gpkit/variables.py
Started some attempts to clean up and document substitution. Others welcome to contribute as well.
Related:
-  #267 
-  #268 
-  #279
> Sub improvements

- gpkit/nomials.py
- gpkit/small_classes.py
- gpkit/small_scripts.py
- gpkit/substitution.py
- gpkit/tests/run_tests.py
- gpkit/tests/t_small.py
- gpkit/tests/t_vars.py
- gpkit/variables.py
- gpkit/varkey.py
Ongoing improvements to core (low-level) classes and functions.
Changes:
> Core refactor

- gpkit/tests/pylint.cfg
Ongoing improvement to our pylint configuration. Should be merged periodically when agreement on changes is reached.
> pylint config updates

- gpkit/small_scripts.py
- gpkit/tests/t_small.py
> A wild unit test appeared

- gpkit/nomials.py
- gpkit/tests/t_constraints.py
Address a number of documentation (and some testing) issues for 0.2.0 release milestone.
> Documentation improvements

- gpkit/_mosek/cli_expopt.py
- gpkit/_mosek/expopt.py
- gpkit/tests/t_geometric_program.py
> corrects costs when constants in objective for mosek(_cli)

- setup.py
> setup script pep8

- gpkit/nomials.py
- gpkit/tests/t_constraints.py
- gpkit/tests/t_nomials.py
- gpkit/variables.py
Assorted improvements as discussed in inline comments from #301
> Assorted improvements

- gpkit/tests/t_model.py
> add tests of new SP heuristic, closes #257

- gpkit/__init__.py
- gpkit/model.py
- gpkit/shortcuts.py
- gpkit/tests/t_model.py
- gpkit/tests/t_nomials.py
> Use 'with' environment to enable signomials

- gpkit/model.py
- gpkit/signomial_program.py
- gpkit/tests/t_model.py
> Revert "Possible solution to address #336"

- gpkit/model.py
- gpkit/signomial_program.py
- gpkit/tests/t_model.py
Reverts convexopt/gpkit#344
very sloppy behavior on my part -- really sorry.
Let's go ahead and merge #337 (which has already been merged; this reverts my revert),
and we can address further issues in follow-on tickets and PRs.
> Revert "Revert "Possible solution to address #336""

- gpkit/signomial_program.py
- gpkit/tests/t_model.py
> Sig loop condition

- gpkit/signomial_program.py
- gpkit/tests/t_model.py
> refactor signomial loop conditional

- gpkit/solution_array.py
- gpkit/tests/t_model.py
> GP sensitivity test

- gpkit/_cvxopt.py
- gpkit/_mosek/cli_expopt.py
- gpkit/_mosek/expopt.py
- gpkit/geometric_program.py
- gpkit/model.py
- gpkit/small_classes.py
- gpkit/varkey.py
> capture stdout to get log from solvers

- gpkit/__init__.py
> allow units to be disabled and then re-renabled

- gpkit/__init__.py
- gpkit/nomial_data.py
- gpkit/nomials.py
- gpkit/small_scripts.py
- gpkit/substitution.py
- gpkit/tests/t_model.py
- gpkit/tests/t_nomials.py
- gpkit/tests/t_sub.py
philosophy:
* every nomial_data.units is either UnitContainer, None, or list thereof. 
* (this means that every Signomial.units is either UnitsContainer or None)
* VarKey.units is a Quantity, string or KeyError
* cs are always numpy arrays or Quantities.
fixes #374
> fix nomial equality

- gpkit/model.py
trivial change solves the issue; current print output is not going to win any art awards.
> remove pformat, resolves #371

- gpkit/nomials.py
- gpkit/tests/t_nomials.py
> move numeric comparisons from Monomial to Signomial, resolves #392

- gpkit/interactive/ractor.py
- gpkit/interactive/widget.py
related to #405.
longer-term solution to #405 desperately needed
> patches to get widgets marginally working

- docs/source/examples/simpleflight.py
- docs/source/examples/simpleflight_output.txt
I deleted the gpkit.units if statements and added 2 variables that I labeled as coefficients. I got the same results as on the website.
> Cleaned Simple Flight

- .gitmodules
This branch uses a "git submodule" to implement the `gpkit/models` folder. The submodule is treated as a nested git repository (hosted at https://github.com/aeroa/gpkit-models), which is updated with `git submodule update --remote`.
Pros of using submodules:
* Separate issue tracker for gpkit models
Cons of using submodules:
* Have to be manually updated; if we'll always be tracking the current models version, this'll add some
> Demonstration of submodules

- gpkit/model.py
- gpkit/nomial_data.py
- gpkit/nomials.py
- gpkit/posyarray.py
- gpkit/solution_array.py
- gpkit/tests/t_sub.py
- gpkit/variables.py
- gpkit/varkey.py
- model_printing.py
This first draft seems to work, except for using '&' with vectors.
There's two tests which need to be added: one testing everything with vectors, and one testing `Model.varsbyname`
Also needs a few docstrings, documentation, etc.
> model composition

- docs/source/advancedcommands.rst
- docs/source/ipynb/Box/Box.ipynb
- docs/source/ipynb/Box/Box.rst
- gpkit/interactive/__init__.py
- gpkit/interactive/sensitivity_map.py
- gpkit/small_classes.py
- gpkit/solution_array.py
- gpkit/tests/t_solution_array.py
@whoburg this is ready for review (but kinda inconsequential)
@pk Let me know if this is useful!
> add sensitivity map, remove solution_array.sens because it lies

- gpkit/build.py
Closes #416 (confirmed on philippe's computer)
@galbramc, @whoburg, shall we try this with the el capitan test servers?
> Fix MOSEK on macs

- gpkit/_mosek/cli_expopt.py
- gpkit/model.py
@bqpd, this is ready to review pending Jenkins. Addresses comments in #454
> minor fixes

- gpkit/__init__.py
- gpkit/feasibility.py
- gpkit/geometric_program.py
- gpkit/interactive/__init__.py
- gpkit/interactive/ipywidgets.py
- gpkit/interactive/ractor.py
- gpkit/interactive/widgets.py
- gpkit/model.py
- gpkit/nomials.py
- gpkit/signomial_program.py
- gpkit/solution_array.py
- gpkit/varkey.py
This is a cleaned up version of #452 that includes only the relevant commits not already on master. Closes #291
> Controlpanel

- gpkit/__init__.py
> clean up __init__

- gpkit/__init__.py
- gpkit/gpkit_constants.txt
- gpkit/gpkit_units.txt
See https://github.com/aeroa/gpkit-models/pull/24
> Define units from GPkit folder

- gpkit/model.py
The low hanging fruit from issue #480 
This time without 7 empty commits (yay)
> Low hanging fruit from issue 480 (Cleaner version)

- gpkit/__init__.py
- gpkit/tests/t_nomials.py
> resolve issue 492

- docs/source/installation.rst
> add reinstall/update instructions to docs

- gpkit/constraints.py
- gpkit/geometric_program.py
- gpkit/nomials.py
- gpkit/signomial_program.py
- gpkit/tests/t_constraints.py
- gpkit/tests/t_sub.py
@bqpd, please review. Ready for merging.
> pep8, minor changes

- gpkit/interactive/widgets.py
> keep current slider value when max jumps below min during typing

- gpkit/tests/helpers.py
- gpkit/tests/t_examples.py
Some changes needed for gpfit to use gpkit test helpers
see https://github.com/hoburg/gpfit/issues/30
> make test helpers usable by external packages

- pylint.sh
> add gpkit to PYTHONPATH for CI

- gpkit/geometric_program.py
added a docstring; this PR is to merge into the `issue526` branch in progress.
@bqpd, please review.
> documentation for GeometricProgram._compile_result, fixes #539

- gpkit/geometric_program.py
> add tolerance to dual variable nonnegativity check, closes #528

- gpkit/tests/t_nomials.py
Closes #544. @galbramc, I think this branch will pass tests with pints 0.7
> fix tests for pints 0.7

- docs/source/examples/beam.py
- gpkit/model.py
- gpkit/small_classes.py
- gpkit/solution_array.py
- gpkit/tests/t_examples.py
- gpkit/tests/t_solution_array.py
- gpkit/tests/t_sub.py
Closes #541.
@whoburg, note that this implements Quantity substitution but does not test it outside of cvxopt cost functions.
> Units in solutions

- .gitmodules
Once more the correct way. How about this?
> remove gpkit-models from gpkit; it should be a separate package

- MANIFEST
... to fix our currently failing tests on master branch
> remove gpkit/models from manifest too

- gpkit/build.py
@galbramc, see if this fits your needs...
> get build dir from environment variable GPKITBUILD if it exists

- gpkit/__init__.py
- gpkit/keydict.py
- gpkit/tests/t_examples.py
- gpkit/tests/t_model.py
- gpkit/tests/t_nomial_array.py
- gpkit/tests/t_nomials.py
- gpkit/tests/t_small.py
- gpkit/tests/t_solution_array.py
- gpkit/tests/t_tools.py
- gpkit/tests/t_vars.py
> remove old docstring info, unneeded pylint suppression

- gpkit/nomials/nomial_math.py
- gpkit/tests/t_model.py
> simplify gp after substitution

- gpkit/nomials/substitution.py
- gpkit/tests/t_sub.py
> Quantity substitution and a few tests

- gpkit/nomials/data.py
- gpkit/nomials/substitution.py
- gpkit/tests/t_sub.py
There was a bug with pints 0.6 in monomial substitution. Fixed that and did a bit of cleanup...
> fix dimensionless varkey/monomial substitution, add test

- gpkit/constraints/link.py
- gpkit/tests/t_constraints.py
> fix duplicate-substitution conflict during linking

- gpkit/constraints/prog_factories.py
- gpkit/geometric_program.py
- gpkit/tests/t_model.py
> fix united-cost issue

- gpkit/constraints/tight.py
- gpkit/tests/t_constraints.py
Implements a tight constraint set that checks whether the left and right side of an equality are equal after substituting in the solved values.
@whoburg ready for review
> Tight Constraint Set

- gpkit/constraints/set.py
- gpkit/constraints/signomial_program.py
- gpkit/tests/t_constraints.py
Ready for review @whoburg @bqpd
> proposed fix to issue #593

- gpkit/interactive/chartjs.py
> initial prototype of interactive javascript charts, with @bqpd

- gpkit/nomials/nomial_math.py
> add error for tautological constraints

- gpkit/tests/t_sub.py
this is a basic unit test for linked sweeps. ready for quick review and merging.
> basic linked sweeps unit test

- gpkit/small_classes.py
- gpkit/small_scripts.py
- gpkit/tests/t_small.py
- gpkit/tests/t_sub.py
> Fix united sweep

- gpkit/nomials/data.py
- gpkit/nomials/nomial_core.py
- gpkit/nomials/nomial_math.py
- gpkit/tests/t_nomials.py
> fix ambiguous and Variable diffs

- gpkit/geometric_program.py
> print warning about unused substitutions

- gpkit/geometric_program.py
Proposed fix to #528 (small typo).
Ready for very quick review @whoburg
> Proposed issue 528 fix

- gpkit/constraints/signomial_program.py
- gpkit/nomials/nomial_math.py
- gpkit/tests/t_model.py
> improve Signomial=>Posy simplifcation, fixing #610

- gpkit/geometric_program.py
per https://github.com/hoburg/gpkit/commit/85d7b3bda0f34de1f5030f62119eeaf3428758d3#commitcomment-17013935.
> add spaces to error messages in geometric_program

- docs/source/installation.rst
- setup.py
> add and document numpy version requirement, closing #546

- gpkit/geometric_program.py
After https://github.com/hoburg/gpkit/commit/516b31cabf732b21edcda66508858c820246683e#commitcomment-16960993
> only process the root constraint's process_result

- docs/source/installation.rst
- gpkit/build.py
- gpkit/geometric_program.py
- setup.py
This should fix the builds on the Windows 10 VM
> Fixes in build.py for Windows

- gpkit/constraints/tight.py
I'd like to have a kwarg that allows it to print a warning instead of throwing an error.
This is my proposed change.
> Gentle TightConstraintSet kwarg

- gpkit/nomials/nomial_math.py
> print guilty nomials in unit mismatch error

- gpkit/__init__.py
- gpkit/constraints/costed.py
- gpkit/constraints/set.py
> add user-friendly ConstraintSet class for inheriting from, closes #607

- gpkit/nomials/nomial_math.py
- gpkit/nomials/substitution.py
> remove circular import

- docs/source/installation.rst
This is ready for review and could use some work from someone with a good eye for graphics / markdown.
> update install instructions with recommendations from @galbramc

- gpkit/constraints/set.py
- gpkit/geometric_program.py
- gpkit/interactive/sensitivity_map.py
Doing this made me notice we have triply-repeated code in latex array generation
> [ll] to {ll} in array latex

- gpkit/nomials/nomial_math.py
> skip tautological monomial constraints, closing #633

- LICENSE
- setup.py
> update copyright year and group name

- gpkit/constraints/model.py
- gpkit/constraints/set.py
- gpkit/constraints/signomial_program.py
- gpkit/constraints/tight.py
- gpkit/geometric_program.py
- gpkit/nomials/nomial_math.py
- gpkit/tests/t_constraints.py
> simple profiling improvements

- docs/source/advancedcommands.rst
Ready for review.  
Made example in docs showing and explaining how to free fixed variables.
> document freeing fixed vars with example

- gpkit/solution_array.py
ready for review @whoburg @bqpd
> Proposed fix to issue #561

- docs/source/signomialprogramming.rst
(oops)
ready for review/merging
> external call docs: fix changed filesnames

- gpkit/constraints/tight.py
Addresses issue #691 
Ready for review @whoburg @bqpd
> Cleaner tight constraint message

- gpkit/solution_array.py
@bqpd ready for the swiftest of reviews
closes #701
> fix issue #701

- gpkit/interactive/plotting.py
Only plots cost convergence instead of trying to plot variables convergence
Ready for review @whoburg  @bqpd
> A more useful plot_convergence

- gpkit/interactive/sensitivity_map.py
@bqpd ready for review but more importantly this needs a more thorough refactor
sensitivity map currently does not work for the 1682 model due to vector constants, and this does not yet address that problem
> band-aid fixes for sensitivity map -- needs more thorough refactor

- docs/source/examples/external_sp_output.txt
- docs/source/examples/simple_sp_output.txt
- docs/source/examples/sin_approx_example_output.txt
- gpkit/solution_array.py
> don't print an empty sensitivities table

- gpkit/nomials/nomial_math.py
- gpkit/tests/t_constraints.py
- gpkit/tests/t_model.py
> allow tautological monomial equalities (with unit test)

- gpkit/solution_array.py
> don't create meaningless sensitivities, closes #450

- gpkit/constraints/prog_factories.py
- gpkit/solution_array.py
- gpkit/tests/t_sub.py
Closes #707, closes #700, ready for review.
> fix errors when a sweep with skip failures solves once or no times

- gpkit/constraints/set.py
temporary patch for issue 724, planning to merge if passing CI
> patch issue 724 by sorting

- gpkit/_cvxopt.py
- gpkit/geometric_program.py
> remove unnecessary cvxoptimize_fn wrapper

- gpkit/tools/fmincon.py
Improved tool for generating `fmincon` code, as used in the final version of my thesis.
Changes include:
- auto-generating initial guesses given the type of initial guess requested
- Specifying things like the algorithm to use and whether or not to use gradients as kwargs
Ready for review @whoburg @bqpd
> Fmincon improvements

- gpkit/interactive/plotting.py
The x axis starts from iteration 1 instead of iteration 0, for less ambiguity and more readability.
This is the code that was used in the final version of my thesis.
Ready for a cursory review @whoburg @bqpd
> A very small plot_convergence improvement

- gpkit/interactive/plotting.py
improving sensitivity plotting
ready for review. any other improvements we want to make while we're at it?
> add some options to sensitivity plots

- gpkit/__init__.py
- gpkit/constraints/tight.py
- gpkit/geometric_program.py
- gpkit/nomials/__init__.py
- gpkit/nomials/nomial_math.py
- gpkit/solution_array.py
- gpkit/tests/t_model.py
- gpkit/tests/t_nomials.py
> lots of little fixes

- gpkit/nomials/nomial_math.py
- gpkit/tests/t_model.py
This is a simple fix to #748. Also tweaked a test such that this issue would have been caught by unit tests.
Ready for review and merging after passing CI.
> fix #748 -- list in SignomialInequality.nomials

- gpkit/tests/helpers.py
needed for #571.
Planning to merge if tests pass
> use default_solver instead of mutating installed_solvers

- gpkit/small_classes.py
Couldn't help myself. Ready for merge @bqpd @whoburg.
> fixes minor typos

- gpkit/constraints/costed.py
- gpkit/constraints/set.py
- gpkit/constraints/single_equation.py
- gpkit/nomials/array.py
- gpkit/nomials/nomial_math.py
- gpkit/nomials/substitution.py
- gpkit/tests/t_sub.py
> no alternate sub syntax

- docs/source/examples/beam.py
- docs/source/examples/external_sp.py
- docs/source/examples/simple_box.py
- docs/source/examples/simple_sp.py
- docs/source/examples/simpleflight.py
- docs/source/examples/sin_approx_example.py
- docs/source/examples/water_tank.py
- gpkit/_mosek/expopt.py
- gpkit/constraints/prog_factories.py
> don't print table automatically, print timing

- gpkit/tests/t_vars.py
- gpkit/varkey.py
> fix units creation bug

- gpkit/geometric_program.py
The ldl solver is much better at handling rank issues. See #789.
> use ldl kkt solver by default for cvxopt

- gpkit/constraints/set.py
- gpkit/constraints/signomial_program.py
- gpkit/geometric_program.py
- gpkit/nomials/nomial_math.py
> Don't generate constraint sensitivities until we have a reason

- .pylintrc
- gpkit/constraints/set.py
- gpkit/tests/t_sub.py
closes #786 
does not work for vectorvariables.
> getitem only returns top variable

- gpkit/pint/usd_cpi.txt
> add 2015 CPI

- gpkit/constraints/set.py
> warn of booleans in constraintset

- gpkit/small_classes.py
> convert united solutions back to original units

- gpkit/tests/t_solution_array.py
> add unit test for issue 809

- gpkit/nomials/nomial_math.py
This should make things cleaner on the `equality` branch.
> common code for x0 defaults in SPs

- gpkit/_mosek/expopt.py
- gpkit/build.py
- gpkit/interactive/plotting.py
- gpkit/interactive/ractor.py
- gpkit/interactive/sensitivity_map.py
- gpkit/interactive/widgets.py
- gpkit/modified_ctypesgen.py
- gpkit/nomials/nomial_core.py
- gpkit/nomials/substitution.py
- gpkit/nomials/variables.py
- gpkit/small_classes.py
- gpkit/small_scripts.py
- gpkit/tests/helpers.py
- gpkit/tests/t_model.py
> clobber pylint errors

- .pylintrc
- gpkit/constraints/signomial_program.py
> add x0s to each gp in SP.gps

- gpkit/constraints/set.py
- gpkit/nomials/variables.py
- gpkit/tests/t_constraints.py
> get vector variables out of a model properly

- docs/source/examples/external_constraint.py
- gpkit/constraints/signomial_program.py
- gpkit/exceptions.py
- gpkit/geometric_program.py
- gpkit/nomials/nomial_math.py
- gpkit/tests/t_constraints.py
- gpkit/tests/t_model.py
> add exception class InvalidGPConstraint

- docs/apidoc.sh
- docs/source/autodoc/gpkit.rst
- docs/source/conf.py
> get apidocs building on sphinx and macs

- gpkit/interactive/plotting.py
A starting point for fixing #849 @bqpd @whoburg
> proposed fix to #849

- gpkit/constraints/prog_factories.py
- gpkit/small_classes.py
- gpkit/solution_array.py
- gpkit/tests/t_model.py
- gpkit/tests/t_sub.py
WIP resolving #800. So far this just adds an aspirational test. Work on giving SolutionArray["cost"] units should be done on this PR branch.
> (in progress): sol["cost"] should have units

- gpkit/constraints/linked.py
- gpkit/tests/t_constraints.py
closes https://github.com/hoburg/gpkit-models/issues/79
> exclude variables by name as well as by string

- gpkit/small_classes.py
Closes https://github.com/hoburg/gpkit-models/issues/84
> only convert units when in united subdict

- docs/source/gettingstarted.rst
- docs/source/ipynb/Box/Box.ipynb
- docs/source/ipynb/Box/Box.rst
- gpkit/solution_array.py
- gpkit/tests/t_solution_array.py
> remove SolutionArray.sens

- gpkit/tests/t_tools.py
- gpkit/tools/tools.py
Added a `te_secant` function which mirrors `te_exp_minus1`
> Added secant taylor expansion tool

- gpkit/geometric_program.py
ready for review
(`model.feasibility` no longer exists)
> reword outdated error message

- gpkit/tests/t_examples.py
Test for issue #770 
ready for review and merging
> test for nans in beam output

- gpkit/solution_array.py
> don't try to print a latex table without any lines

- docs/source/installation.rst
- setup.py
> Set minimum numpy version to 1.8.1

- gpkit/small_scripts.py
- gpkit/tests/t_small.py
minor simplifications. passes all tests, so if these changes are unacceptable let's add test(s) to catch the issue(s).
> simplify unitstr

- docs/source/examples/beam_output.txt
- docs/source/examples/unbounded_output.txt
- gpkit/constraints/bounded.py
- gpkit/constraints/costed.py
- gpkit/constraints/linked.py
- gpkit/constraints/model.py
- gpkit/constraints/prog_factories.py
- gpkit/constraints/set.py
- gpkit/constraints/signomial_program.py
- gpkit/constraints/single_equation.py
- gpkit/constraints/tight.py
- gpkit/geometric_program.py
- gpkit/keydict.py
- gpkit/nomials/nomial_math.py
- gpkit/nomials/substitution.py
- gpkit/small_classes.py
- gpkit/solution_array.py
- gpkit/tests/helpers.py
- gpkit/tests/t_sub.py
They broke some untested features / assumptions on master
> revert ba9c35f, f8422c4, and 9ef0abc

- docs/source/autodoc/gpkit.constraints.rst
- docs/source/autodoc/gpkit.rst
- docs/source/autodoc/gpkit.tools.rst
- docs/source/releasenotes.rst
> update release notes and autodoc

- docs/source/gettingstarted.rst
- docs/source/gp101.rst
- docs/source/gpkit101.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/signomialprogramming.rst
> small docs wording changes, removed mention of 32b Win

- docs/source/advancedcommands.rst
- docs/source/autodoc/gpkit.constraints.rst
- docs/source/autodoc/gpkit.rst
- docs/source/autodoc/gpkit.tools.rst
- docs/source/debugging.rst
- docs/source/examples/primal_infeasible_ex1.py
- docs/source/examples/primal_infeasible_ex2.py
- docs/source/index.rst
- gpkit/_mosek/cli_expopt.py
- gpkit/constraints/tight.py
- gpkit/solution_array.py
- gpkit/tests/t_examples.py
@mayork, @whoburg, I pulled my favorite parts out of #823 and rewrote them a bit. Documentation is hard!
(ready for review)
> add "debugging" section & examples to the docs to explain feasibility

- docs/source/citinggpkit.rst
- docs/source/installation.rst
- gpkit/build.py
Here's a PR where we can collect minor fixes to the docs as we notice them
> small changes

- gpkit/constraints/single_equation.py
- gpkit/nomials/nomial_math.py
> cleanup operator overloading and fix arrayconstraint subs/latex

- docs/source/examples/beam_output.txt
- gpkit/constraints/prog_factories.py
- gpkit/geometric_program.py
- gpkit/keydict.py
- gpkit/nomials/substitution.py
- gpkit/small_classes.py
- gpkit/solution_array.py
- gpkit/tests/helpers.py
- gpkit/tests/t_solution_array.py
- gpkit/tests/t_sub.py
To be rebased after #953 is merged.
Closes #837
> Solarraybugs

- gpkit/interactive/widgets.py
- gpkit/solution_array.py
- gpkit/varkey.py
Maybe these can make it into 0.5.0
> minor code cleanups

- gpkit/nomials/array.py
> implement O(N) sums and monomial products

- docs/source/installation.rst
> update cvxopt install instructions

- gpkit/constraints/tight.py
> change Tight tol to 1e-2

- LICENSE
- docs/source/conf.py
- setup.py
> change copyright

- gpkit/tests/t_model.py
- gpkit/tests/t_solution_array.py
> small test for issue 819

- gpkit/tests/t_model.py
> test that values are the same as substitutions in an SP

- gpkit/tests/t_model.py
> add initially-infeasible sp

- gpkit/tools/spdata.py
as used to create examples in https://github.com/hoburg/gpkit-models/issues/8
> add spdata to tools

- gpkit/tests/from_paths.py
- gpkit/tests/test_repo.py
@whoburg, ready for review. No longer high priority.
> Fix remote skipsolvers

- gpkit/interactive/widgets.py
- gpkit/small_scripts.py
- gpkit/solution_array.py
- gpkit/tests/t_solution_array.py
> update controlpanel, allow printing ohm and delta for fancy units

- gpkit/nomials/nomial_math.py
- gpkit/varkey.py
> Make things unitless, not pint-dimensionless

- gpkit/constraints/geometric_program.py
- gpkit/keydict.py
- gpkit/nomials/substitution.py
> lazy keymapping

- docs/source/signomialprogramming.rst
> remove wrong docs

- gpkit/interactive/widgets.py
> proper default arg for controlpanel showvars

- docs/source/examples/external_sp2.py
- docs/source/examples/plot_sweep1d.py
- docs/source/examples/plot_sweep1d_output.txt
> small docs fixes

- gpkit/nomials/nomial_math.py
> ensure dimensionlessness of e and m0 in mono_approx

- gpkit/constraints/geometric_program.py
- gpkit/constraints/signomial_program.py
> add soltime to solution

- gpkit/constraints/costed.py
- gpkit/nomials/nomial_core.py
> add prod/sum compat back to nomials

- docs/source/examples/relaxation_output.txt
- gpkit/constraints/relax.py
> compute sensitivities to original value in ConstantsRelaxed

- gpkit/constraints/geometric_program.py
> allow GP solves to return near_dual_feas solutions

- docs/source/examples/performance_modeling.py
- gpkit/constraints/set.py
- gpkit/varkey.py
(tested in the performance_modeling example)
> add topvar method to get the variable with the same naming

- docs/source/autodoc/gpkit.rst
- docs/source/examples/model_var_access.py
- docs/source/examples/model_var_access_output.txt
- docs/source/modelbuilding.rst
- gpkit/tests/t_examples.py
@bqpd this documents and tests variable access. Ready for review.
> document and test ways to access Variables in a Model

- docs/source/advancedcommands.rst
- gpkit/constraints/geometric_program.py
- gpkit/constraints/set.py
- gpkit/nomials/nomial_core.py
- gpkit/nomials/variables.py
- gpkit/repr_conventions.py
- gpkit/small_scripts.py
- gpkit/solution_array.py
- gpkit/tests/t_small.py
- gpkit/tests/t_sub.py
- gpkit/tests/t_vars.py
- gpkit/varkey.py
> small issue fixes

- gpkit/constraints/costed.py
- gpkit/constraints/signomial_program.py
@whoburg. @mjburton11 , fixes #1131. Ready for review.
> don't re-bring costvals into sp substitutions

- .pylintrc
- docs/source/examples/external_sp2.py
- gpkit/_cvxopt.py
- gpkit/build.py
- gpkit/constraints/geometric_program.py
- gpkit/constraints/prog_factories.py
- gpkit/constraints/set.py
- gpkit/constraints/sigeq.py
- gpkit/constraints/signomial_program.py
- gpkit/interactive/sensitivity_map.py
- gpkit/interactive/widgets.py
- gpkit/keydict.py
- gpkit/nomials/array.py
- gpkit/nomials/data.py
- gpkit/nomials/nomial_math.py
- gpkit/nomials/substitution.py
- gpkit/nomials/variables.py
- gpkit/small_classes.py
- gpkit/small_scripts.py
- gpkit/solution_array.py
- gpkit/tools/autosweep.py
- gpkit/tools/tools.py
Pylint was upgraded to version 1.7.2, and introduced new warnings.
> Suppressed pylint warning

- gpkit/tests/t_tools.py
- gpkit/tools/fmincon.py
PR to get latest version of fmincon code merged
> Fmincon update

- gpkit/nomials/variables.py
- gpkit/tests/t_model.py
- gpkit/tests/t_vars.py
- gpkit/tools/tools.py
Closes #1138 
@whoburg ready for review
> Symmetric Variable / VarKey ==

- docs/source/installation.rst
@whoburg, I'm going to merge this real quick, but feel free to review!
> Update MOSEK install link in documentation

- docs/source/citinggpkit.rst
- docs/source/debugging.rst
- docs/source/examples.rst
- docs/source/installation.rst
- gpkit/tests/test_repo.py
- setup.py
> change repo url from hoburg to convexengineering

- gpkit/nomials/math.py
- gpkit/tests/t_constraints.py
@bqpd Would it be possible to give this a quick review and merge so we can get back to master?
> Unit-ed dimensionless vars

- gpkit/constraints/model.py
- gpkit/constraints/set.py
- gpkit/keydict.py
- gpkit/nomials/variables.py
- gpkit/tests/t_sub.py
Closes #1179
accompanied by https://github.com/convexengineering/gplibrary/pull/125
> Fix linked vector vars, remove need for x == x to get substitutions

- gpkit/constraints/model.py
- gpkit/constraints/prog_factories.py
- gpkit/constraints/relax.py
- gpkit/constraints/set.py
- gpkit/nomials/substitution.py
> update relaxconsts for linked vars, fix debug

- gpkit/keydict.py
- gpkit/small_scripts.py
- gpkit/solution_array.py
> Use type-aware isnan in solution_array

- gpkit/constraints/gp.py
> fold generate_nula into _compile_result

- gpkit/nomials/map.py
- gpkit/tests/t_sub.py
- gpkit/tools/fmincon.py
> remove string substitutions

- gpkit/tests/from_paths.py
Closes https://github.com/convexengineering/gplibrary/issues/140
> test/from_paths.py: same cwd at import and test run

- gpkit/constraints/gp.py
- gpkit/nomials/substitution.py
> fix substitution of quantities for indexed vectorvars

- gpkit/nomials/map.py
- gpkit/nomials/math.py
closes #1269. Thanks to @Lewis-Lu for pointing this out on the [gitter](https://gitter.im/gpkit-users/Lobby)!
> better error msg on addition of dimless qty to dimensioned qty

- gpkit/build.py
> allow specification of mosek rootdir with MSKHOME environment variable

- docs/source/examples/x_greaterthan_1_output.txt
- gpkit/keydict.py
- gpkit/solution_array.py
- gpkit/tests/t_solution_array.py
> sol() now always returns Quantities (even dimensionless ones)

- gpkit/tests/t_tools.py
- gpkit/tools/docstring.py
> allow vectorvariables to be parsed without needing variables

- gpkit/build.py
> have build script start by moving to its own directory

- docs/source/examples/docstringparsing_output.txt
- gpkit/tools/docstring.py
> Improve docstring errors and parsing

- gpkit/nomials/math.py
> print errors when an infeasible monomialequality is created

- gpkit/interactive/sankey.py
- gpkit/keydict.py
- gpkit/nomials/math.py
> sankey working on individual SP GPs, as_posyslts returns copy

- docs/source/examples/simple_box_output.txt
- docs/source/examples/simpleflight_output.txt
- docs/source/examples/sp_to_gp_sweep.py
- docs/source/examples/sp_to_gp_sweep_output.txt
- gpkit/constraints/costed.py
- gpkit/constraints/gp.py
- gpkit/constraints/prog_factories.py
- gpkit/keydict.py
- gpkit/nomials/math.py
- gpkit/nomials/variables.py
- gpkit/small_scripts.py
- gpkit/solution_array.py
- gpkit/tests/t_examples.py
- gpkit/tests/t_sub.py
- setup.py
Closes #1245
Closes #1184 
Closes #1206
> don't transmute sig ineqs when they become posy

- gpkit/keydict.py
Closes https://github.com/convexengineering/solar/issues/25
> init keydict variables before updating

- gpkit/nomials/math.py
> specify warning on approximation overflow

- gpkit/constraints/bounded.py
Closes #1250
@mjburton11 this makes the output of #1250 quite reasonable on my computer...does it do anything for you?
> don't bound variables that aren't in any constraints

- gpkit/constraints/gp.py
Reverts convexengineering/gpkit#1307
Closes #1308
> Revert "change cvxopt refinement parameter"

- gpkit/keydict.py
closes #1267 
@1ozturkbe note that network.py still falls on this branch in the draw step, but it does solve
> cast int arrays to floats

- gpkit/constraints/gp.py
- gpkit/keydict.py
Closes #1325
as noticed by @1ozturkbe
> varkeys for GPs

- gpkit/solution_array.py
Closes #1318
@1ozturkbe, the issue was that some constants are in the solution array even if they are not in any constraints, but only variables in constraints get sensitivities.
> fix for variables not in sensitivities

- gpkit/solution_array.py
- gpkit/tests/t_model.py
>  fix and unify almost_equal and diff for 0 substitutions 

- gpkit/build.py
> Update build message to note potential wrong mingw

- gpkit/constraints/relax.py
> fix linked-var gradients carryover from previous solves

- .pylintrc
- gpkit/_mosek/cli_expopt.py
@mjburton11 this may obviate the need for that mosek_cli directory hack
closes #1380
> fix dot solutions for mosek_cli

- docs/source/examples/relaxation_output.txt
- gpkit/globals.py
> number paths, not models

- gpkit/constraints/model.py
- gpkit/constraints/sgp.py
- gpkit/tests/t_constraints.py
- gpkit/tests/t_model.py
This implements an updated signomial algorithm which currently does not work terribly well. But always nice to have the option. Let me know if you have opinions about the implementation @bqpd.
> PenaltyCCP algorithm.

- gpkit/build.py
> a less concerning mosek_cli build message

- gpkit/__init__.py
- gpkit/build.py
> version in build script

- docs/source/examples/performance_modeling_output.txt
- gpkit/solution_array.py
> clarify constraint differencing

- gpkit/keydict.py
> don't wrap arrays for singleton string keys

- gpkit/keydict.py
- gpkit/solution_array.py
> avoid DeprecationWarning

- docs/source/examples/simple_sp.py
- docs/source/signomialprogramming.rst
- gpkit/constraints/set.py
- gpkit/constraints/sgp.py
- gpkit/keydict.py
> Clean user-submitted x0s during localsolve

- .pylintrc
- docs/source/examples/issue_1522.py
- gpkit/constraints/gp.py
- gpkit/constraints/prog_factories.py
- gpkit/constraints/sgp.py
- gpkit/tests/t_model.py
- gpkit/tests/t_nomials.py
> deduplicate gp hmaps

- gpkit/constraints/gp.py
- gpkit/constraints/model.py
- gpkit/constraints/prog_factories.py
- gpkit/solvers/cvxopt.py
- gpkit/tests/t_model.py
> deduplicate in cvxopt presolve instead, add test

- setup.py
as discovered by @pgkirsch during a fresh install. Closes #1558.
> dependency fixes

- docs/source/installation.rst
Fixed several broken links in `installation.rst`.
> Fresh install fixes
