convexengineering/gpkit

gpkit/tests/t_vars.py

Note that `range(1, 3)` is `[1, 2]`, whereas `range(3)` is `[0, 1, 2]`.

rename tests and fix range bug

---

gpkit/geometric_program.py
gpkit/small_scripts.py

This could still use work, but I took a shot at refactoring some of the table printing. In particular
* now sorting so that Vectors and non-vectors come in separate chunks
* can now optionally print in fixed-width columns.
* made many of the formatting strings explicit parameters
* removed code that prints constant-valued vectors as if they are scalars, as this seems possibly misleading
Here's an example of the current output for `print sol.table()`
```
Cost
0.00474 
Variables
CDA : 0.005                              [m**2]    projectile drag area
R : 211                                [m]       range               
Vmax : 100                                [m/s]     max firing velocity 
g : 9.8                                [m/s**2]  gravity             
m : 1 …
```

refactor result table printing

---

gpkit/posyarray.py
gpkit/tests/t_posy_array.py

* implement new convenience methods useful for finite-differencing `PosyArray`s
Example usage:
```python
from gpkit import VectorVariable
x = VectorVariable(10, 'x', 'm')
dx = VectorVariable(10, 'dx', 'm')
constraint = (x >= x.left + dx/2. + dx.left/2.)
```

PosyArray improvements

---

docs/source/advancedcommands.rst
gpkit/__init__.py
gpkit/nomials.py
gpkit/tests/run_tests.py
gpkit/tests/simpleflight.py
gpkit/tests/t_geometric_program.py
gpkit/tests/t_nomials.py

As discussed in #224,
* rename function `enableUnits()` --> `enable_units()`
* rename function `disableUnits()` --> `disable_units()`
* create functions `enable_signomials()` and `disable_signomials()`, to replace current practice of modifying the module-level boolean variable `gpkit.enable_signomials`.

Issue224 -- standardizing method names

---

gpkit/_mosek/cli_expopt.py
gpkit/_mosek/expopt.py
gpkit/geometric_program.py
gpkit/tests/t_geometric_program.py

This is a pull request to update `fix_296`, i.e. #304.
- Simplifies cost computation hotfix by doing it in `GeometricProgram._parse_result`
- Adds more cost testing to existing tests
- Updates logic for number of accuracy digits in GP testing

simple hotfix for #296; and add more cost testing

---

gpkit/geometric_program.py
gpkit/model.py

closes #31
Example usage:
```python
In [3]: %paste
from gpkit import Variable, Model
x = Variable("x")
x_min = Variable("x_min", 2)
x_max = Variable("x_max", 1)
m = Model(x, [x <= x_max, x >= x_min])
#m.solve()
m.feasibility_report()
Infeasibility
-------------
overall : 1.41
constraint : [2.0, 1.0]
constant : {x_min: 1.0}
Out[3]: 
{'constants': {x_min: 1.0},
'constraints': [2.0, 1.0],
'overall': 1.414213562373095}
```
The `overall` infeasibility is the number each constraint's less-than side would have to be divided by to make the program feasible. The `constraints` infeasibilities are similar, but specific to each constraint. The `constant` infeasibilities are a set of substitutions that would make the problem feasible, so they're really more a set of "feasibilities".

first feasibility reports

---

README.md

This should add an embedded build status to the main page (I think). Someone needs to push a commit directly to master to test the build.

Added Embeddable Build Status

---

gpkit/nomials.py
gpkit/tests/t_nomials.py

Idea is that Monomial should deal with equality/inequality testing with numeric types...
Could alternatively implement comparison of `NomialData` with numeric types...
Currently fails unit tests, `Monomial.__ne__` is not implemented and falls back on an incorrect implementation by a parent.

Monomial equality refactor

---

gpkit/nomials.py
gpkit/tests/t_constraints.py

This is a (very small) subset of f59f008bd4d4e84889025f08258176cb1eefe, plus a test, to fix #462. @bqpd or @pgkirsch, please either one of you go ahead and merge this if you are happy, assuming it passes Jenkins (it will fail El Capitan testing, which should not prevent merging).

unbreak MonoEQConstraint printing, resolves #462

---

gpkit/geometric_program.py
gpkit/model.py
gpkit/nomial_data.py

This is a first stab at the type of changes needed under #446. There is a little awkwardness due to the fact that GeometricProgram implements a different `__init__` signature than `NomialData` (which it inherits from), but this PR gets around that issue.

implement fromnomials for NomialData construction

---

gpkit/__init__.py
gpkit/varkey.py

```python
import gpkit
x = gpkit.Variable("x", model="test")
x  # prints without modelname
gpkit.settings["latex_modelname"] = True
x  # prints with modelname
```

allow tweaking modelname printing in latex

---

gpkit/substitution.py

```
In [1]: import gpkit
In [2]: x = gpkit.Variable("x", "m")
In [3]: y = gpkit.Variable("y", "volt")
In [4]: x.sub(x, y)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[...]
/home/eburn/projects/src/gpkit/gpkit/substitution.pyc in substitution(nomial, substitutions, val)
204                                          " those of the original '%s' [%s]." %
205                                          (sub, sub.units.units,
--> 206                                           var, var.units.units))
207                 exps_[i] += x*sub.exp
208                 cs_[i] *= mag(sub.c)**x
ValueError: units of the substituted monomial 'y [V]' [volt] are not compatible with those of the original 'x' …
```

better unit-mismatch-during-sub error message

---

.pylintrc

pylint by default requires variable names to be three or more characters. This reduces that requirement to one character.

pylint: allow single character variable names

---

.pylintrc

- increase max branches from 12 to 15
- line length 80 char
- docstrings not required for unit test methods

assorted pylint tweaks

---

gpkit/nomials.py
gpkit/tests/t_nomials.py

here's a simple fix we can discuss. disadvantage is that perhaps the user should have to put calls to diff in a `SignomialsEnabled` environment

strawman resolution to issue534

---

.pylintrc
gpkit/__init__.py
gpkit/geometric_program.py

- avoids calling `np.exp` for non-optimal solutions (which resulted in a `RuntimeWarning` in #526)
- still allows user to create the results dict for non-optimal models as described in error message edited in this PR

reorganize GeometricProgram.solve(); fixes #526

---

README.md
docs/source/citinggpkit.rst
docs/source/installation.rst
gpkit/tests/t_solution_array.py

Final cleanup to close out #509 
- show Jenkins status for all three machines on README
- eliminate duplicate debugging info from install instructions
- update debugging info with other potential failure modes as suggested by @galbramc

CI status on README; install instructions

---

setup.py

Currently "pip install -e" does not cause gpkit to rebuild. I think the safest thing to do is always rebuild, especially since your documentation lists this as a method for staying up to date.

Added "develop" to trigger a build in setup.py

---

gpkit/constraints/costed.py
gpkit/constraints/link.py
gpkit/constraints/model.py
gpkit/constraints/set.py
gpkit/constraints/single_equation.py
gpkit/nomials/data.py
gpkit/nomials/nomial_math.py
gpkit/nomials/substitution.py
gpkit/tests/t_constraints.py
gpkit/tests/t_nomials.py
gpkit/tests/t_sub.py
gpkit/varkey.py

With `gas_hale`, latest commit / master
| Operation | Time (%) |  Biggest cause of slowness in refactor |
|---|---|---|
| Parse student's code  | 50/47  | ???  | 
| Rename model  | 25/0  | slow NomialData generation | 
| Generate GP | 22/14 | slow Nomial generation | 
| Solve | 10 | the solver (mosek here: cvxopt is 10x slower on my computer) | 
| Compile result | 20/0 | calculating var_senss for each PosyIneq separately | 
We added two new parsing steps: one a proper varkey renaming, the other a recursive result compilation. These are slow: this model changes from spending 86% of its time in GPkit to spending 92% of its time there (or 37/53% with cvxopt). Honestly, the big problem is how slow we are on the user-given code.
I'm still in favor of merging the …

profile refactor

---

gpkit/nomials/nomial_math.py
gpkit/tests/t_model.py

@bqpd, I think this implementation is a bit faster -- it should be O(len(cs)) instead of O(len(cs)*len(0exps)) for large exps and cs (if we ever encounter them)
also added a test

faster simplify_posy_ineq, add test

---

gpkit/constraints/model.py
gpkit/constraints/prog_factories.py
gpkit/constraints/set.py
gpkit/constraints/signomial_program.py
gpkit/interactive/widgets.py

Sub discussions:
- resolved by just calling it a regular SP for now and requesting that example code fail when called as a GP if it wants to work with controlpanel.
Up-to-date example:
```python
from gpkit import VectorVariable, Variable, units, SignomialProgram, Model
import gpkit
from gpkit.constraints.set import ConstraintSet
Re = Variable("Re", 1e6, "-", "Reynolds Number")
CL = Variable("C_L", "-", "Lift Coefficient")
CLmax = Variable("C_{L,max}", 1.0, "-", "Lift Coefficient")
CD = Variable("C_D", "-", "Drag Coefficient")
def xfoil(x0):
return [CD >= 0.01 + .03*CL**2]
class AeroModel(ConstraintSet):
def as_posyslt1(self):
raise ValueError("AeroModel is not allowed to solve as a GP.")
def as_gpconstr(self, x0):
gpconstr = super(AeroModel, self).as_gpconstr(x0)
if x0 and x0["Re"] >= …
```

Call external code during localsolve

---

gpkit/interactive/widgets.py

This fixes a carry-over problem in interactive from 4c63942a90dd9f05d70ee0aa02e9ce3dbfcbd034

switch ValueError to TypeError in interactive

---

gpkit/tests/t_constraints.py

This indirectly helps to prevent issues like #662.

add test for error type raised by SignomialInequality.as_posyslt1

---

gpkit/__init__.py
gpkit/tests/t_small.py

we can remove the `__init__.py` patch once https://github.com/hgrecco/pint/issues/366 is fixed (I'm watching it).
Ready for review.
@pgkirsch

patch and test pint issue 366, fixes #694

---

gpkit/_cvxopt.py
gpkit/geometric_program.py
gpkit/tests/t_model.py

Fixed a bug and added a test. See inline comments for more details.

Make it possible to pass arguments to cvxopt solver

---

gpkit/nomials/data.py
gpkit/tests/t_vars.py

found a bug: identical Variables with units have different hashes.
@bqpd, could this explain the problem you were having with getting @pgkirsch's models to run with your refactor in progress?
ready for review after passing CI.

fix bug with hashing of Variables with units; add test

---

gpkit/tests/t_solution_array.py

e-mail chain leading to this (newest to oldest):
```
Units don’t affect that at all; looks like most of the tolerances for mosek default to 1e-8 or smaller, although MSK_DPAR_INTPNT_NL_TOL_REL_GAP  defaults to 1e-6.
http://docs.mosek.com/7.0/capi/The_optimizers_for_continuous_problems.html#ch-lin-opt-tab-nlo-term-cri
I’ll begrudgingly try turning ndigits on that test to 6.
On Aug 6, 2016, at 9:31 AM, Marshall C. Galbraith wrote:
I presume the solver is iterative and has a convergence tolerance. How do unit impact that tolerance?
From: Warren W Hoburg
Sent: Saturday, August 06, 2016 9:27 AM
To: Marshall C. Galbraith
Cc: Edward (Ned) Burnell
Subject: Re: Ubuntu 16
How can we possibly be passing test_call (which has a 10 digit tolerance!) and failing test_call_units?
def test_call(self):
A = …
```

change tolerance for mosek on Ubuntu16

---

docs/source/advancedcommands.rst
docs/source/gettingstarted.rst

Added more detail to the documentation explaining sol["cost"] in the "Getting Started" page under the "Printing Results" section, and fixed two typos I found on the "Advanced Commands" page.

Added sol["cost"] and fixed a couple typos

---

gpkit/keydict.py
gpkit/tests/t_keydict.py
gpkit/varkey.py

I tried doing something fancy, but this worked better. :-/

reduce number of keys to make keydicts faster

---

gpkit/keydict.py
gpkit/tests/t_keydict.py

Found an issue where attempting to access a missing key from a KeyDict causes a state change where future updates and calls to `in` act incorrectly.
MWE is the attached test (also added as a commit to this PR):
```python
def test_failed_getattr(self):
kd = KeyDict()
with self.assertRaises(KeyError):
_ = kd["waldo"]
kd.update({"waldo": 5})
res = kd["waldo"]
self.assertEqual(res, 5)
self.assertIn("waldo", kd)
```
Issue can arise in interactive sessions when someone checks whether something is in a Models'
substitutions dict, gets a KeyError, and then cannot update that key from then onwards.

KeyDict: failed __getitem__ causes state change

---

docs/source/installation.rst

This should help with some confusions I had when helping Arthur Brown get gpkit installed on Windows 10.

Clarifications in windows install instructions

---

gpkit/tests/run_tests.py

one-liner change
on the current master, if you run `python -c "from gpkit.tests import run; run(); from gpkit import Variable; assert Variable('x', 'ft').units is not None"`
you get:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
AssertionError
```
this fixes that.
@bqpd, ready for review

re-enable units after tests

---

docs/source/examples/beam.py
gpkit/__init__.py
gpkit/keydict.py
gpkit/nomials/array.py
gpkit/nomials/nomial_math.py
gpkit/small_classes.py
gpkit/small_scripts.py
gpkit/tests/t_nomials.py
gpkit/tests/t_solution_array.py
gpkit/tests/t_sub.py
gpkit/tests/t_vars.py

This isn't an easy choice to make, but the following didn't work on master with pint 0.7 and something had to be done:
```python
def test_units(self):
"make sure multiplication with units works (issue 492)"
m = 1.2 * gpkit.units.ft * Variable("x", "m")**2
self.assertEqual(type(m), Monomial)
if m.units:
self.assertEqual(m.units, 1*gpkit.units.ft*gpkit.units.m**2)
m = 0.5 * Variable("x", "m")**2 * gpkit.units.kg
self.assertEqual(type(m), Monomial)
if m.units:
self.assertEqual(m.units, 1*gpkit.units.kg*gpkit.units.m**2)
v = 0.5 * VectorVariable(3, "x", "m")**2 * gpkit.units.kg
self.assertEqual(type(v), NomialArray)  # is actually a Quantity...
if v.units:
self.assertEqual(v.units, 1*gpkit.units.kg*gpkit.units.m**2) # ...of units 'kg'!
v = 0.5 * gpkit.units.kg * VectorVariable(3, "x", "m")**2 …
```

drop support for operator overloading with pint Quantity objects

---

gpkit/build.py

Closes #773.
@galbramc, I think this will fix that Windows10 bug as well. 
@norheim, I think this will allow for the use of `mosek_cli` in #959, and will probably be on master today.

don't use python arch to assume system arch

---

gpkit/constraints/model.py

Undoes `__init__` speedups to implement exactly what we had before, because some models using `LinkedConstraintSet` rely upon it.
@whoburg this is a priority to merge, please review.

Full backwards compatibility with Vectorize and NamedVariables

---

README.md

It came to a "Maze found" page on read the docs for me, fixed to working URL.

Fix glossary link

---

gpkit/nomials/data.py
gpkit/tests/from_paths.py
gpkit/tests/helpers.py
gpkit/tests/run_tests.py
gpkit/tests/test_repo.py

@galbramc, the script here seems to work for testing external repositories; just run `python -c "from gpkit.tests.from_paths import run; run()` while in the root of the appropriate repository. At group meeting tomorrow I'll get people to add `TESTS` files to their repositories; where do you want me to stick the `EXTERNAL_REPOSITORIES` file listing these? Perhaps in gpkit-models?

add script to test remote repositories

---

gpkit/constraints/geometric_program.py
gpkit/constraints/signomial_program.py
gpkit/tests/test_repo.py

Using the more-standard `reltol` argument for SPs, and allowing users to just warn of invalid solutions (ocassionally useful for debugging, [here](https://github.com/hoburg/d8/issues/17#issuecomment-274136575) and in robustness development)

Lint for program interfaces

---

gpkit/nomials/data.py
gpkit/nomials/nomial_math.py
gpkit/tests/t_model.py

simplify and fix sensitivites, add test

---

gpkit/keydict.py
gpkit/tests/t_sub.py

closes https://github.com/hoburg/d8/issues/37

convert lists to arrays for tuple indexing

---

gpkit/constraints/set.py

example code from @mjburton11 
```python
" wing.py "
import numpy as np
from gpkit import Variable, Model, SignomialsEnabled, ConstraintSet
from gpkitmodels.GP.aircraft.wing.wing import Wing as WingGP
from gpkit import Variable, Model, Vectorize, SignomialsEnabled
def Wingtest(N=5, lam=0.5, spar="CapSpar", hollow=False):
wing = WingGP(N=N, lam=lam, spar=spar, hollow=hollow)
mw = Variable("m_w", "-", "span wise effectiveness")
with SignomialsEnabled():
constraints = [mw*(1 + 2/wing["AR"]) >= 2*np.pi]
wing.append(constraints)
return wing
w = Wingtest()
print w["m_w"]
```

allow appending to a constraintset

---

docs/source/examples/performance_modeling.py
gpkit/constraints/set.py
gpkit/tests/t_sub.py

Closes #1232
Closes #1175
Replaced #1237

values are used as substitutions only in their first constraintset

---

gpkit/__init__.py
gpkit/globals.py
gpkit/tests/t_sub.py

Closes #1320 
@1ozturkbe, with this PR you can now compare solutions created in the same session by resetting modelnumbers in between with `gpkit.reset_modelnumbers()`

add reset_modelnumbers function

---

gpkit/solution_array.py

Uses the `SolutionArray.parse_showvars` method to parse showvars, instead of a couple of ad-hoc implementations.

properly parse showvars in diff and savecsv

---

gpkit/constraints/sgp.py

Pretty straightforward really. This warning really shouldn't pop up if verbosity=0.

Appropriate verbosity check for 'SP not converging' warning. 

---

.gitignore
docs/source/examples/autosweep.py
gpkit/_cvxopt.py
gpkit/_mosek/mosek_conif.py
gpkit/build.py
gpkit/constraints/gp.py
gpkit/solution_array.py
gpkit/tests/t_constraints.py
gpkit/tests/t_examples.py
gpkit/tests/t_model.py
gpkit/tests/t_solution_array.py

local version of https://github.com/convexengineering/gpkit/pull/1452
This is fantastic, thanks @rileyjmurray! Making a few small changes to pass tests locally & on some of our larger SP models. @1ozturkbe, it seems like it doesn't pass on SPaircraft at present, and fails on robust (as does mosek, though?).

support for mosek 9 (local branch)

---

docs/source/examples/performance_modeling_output.txt
docs/source/examples/relaxation_output.txt
gpkit/constraints/array.py
gpkit/constraints/gp.py
gpkit/constraints/set.py
gpkit/constraints/sgp.py
gpkit/constraints/single_equation.py
gpkit/nomials/array.py
gpkit/nomials/data.py
gpkit/repr_conventions.py
gpkit/solution_array.py
gpkit/tests/t_model.py
gpkit/tests/t_nomial_array.py
gpkit/varkey.py

Closes https://github.com/convexengineering/gpkit/issues/1474
Significantly faster, whoo!

ConstraintSets should contain non-ConstraintSets

---

gpkit/constraints/sgp.py

fix exponents appearing and disappearing from the A matrix

---

gpkit/nomials/math.py
gpkit/solution_array.py

Per #1497
@pgkirsch this halves pickle size without removing any solution information. Between this and the compression I'd expect that 110MB file to drop to less than 10MB.

add SolSavingEnvironment, halving pickle size

---

gpkit/keydict.py

allows substitutions like ```m.substitutions[v[0,2:]] = 1  # or np.ones(v[0,2:].shape)```

Partial vector substitution

---

docs/source/examples/performance_modeling_output.txt
docs/source/examples/relaxation_output.txt
gpkit/constraints/gp.py
gpkit/solution_array.py

Closes #1521
Example output: 
```
Optimal Cost
------------
[ 0.873     1.09      1.61      ]
Swept Variables
---------------
| Aircraft.Wing
rho : [ 0.5       1         2        ]  [lbf/ft²] areal density
Model Sensitivities (sorts models in sections below)
-------------------
+2.79 + [   -     -   +0.1 ] : Mission.FlightSegment.AircraftP.WingAero
+2.51 + [   -     -     -  ] : Mission
+2.43 + [ -0.2    -   +0.3 ] : Mission.FlightSegment.AircraftP
+1.64 + [ -0.5    -   +0.6 ] : Aircraft.Wing
+1.43 + [ -0.6    -   +0.7 ] : Mission.FlightSegment.FlightState
+1.42 + [ -0.2    -   +0.3 ] : Aircraft
+0.97 + [   -     -     -  ] : Aircraft.Fuselage
Free Variables
--------------
| Mission.FlightSegment.AircraftP.WingAero
CD : [ 0.014     0.014     0.0139    0.0139            drag coefficient …
```

Sort solution tables (that aren't already sorted by values) by model sensitivity, an print a model sensitivity table

---

docs/source/examples/performance_modeling.py
gpkit/solution_array.py

pass on import error when testing sankey
